// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvfMm4jMrun3R4hOag1ROVlb8bQhlkQIo',
    appId: '1:502997594403:web:5e9b79a83e44f20b945c96',
    messagingSenderId: '502997594403',
    projectId: 'dw-jobtimer',
    authDomain: 'dw-jobtimer.firebaseapp.com',
    storageBucket: 'dw-jobtimer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzY0LQ98Rt-nuDC59a4KSXaPJQUIIJEsM',
    appId: '1:502997594403:android:9ea6defd0e098456945c96',
    messagingSenderId: '502997594403',
    projectId: 'dw-jobtimer',
    storageBucket: 'dw-jobtimer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj8NJOlVObyZz-1CnDggxlXdWYhRlN7PA',
    appId: '1:502997594403:ios:0f36f160fdb130dc945c96',
    messagingSenderId: '502997594403',
    projectId: 'dw-jobtimer',
    storageBucket: 'dw-jobtimer.appspot.com',
    iosClientId: '502997594403-n4hhqvufier2rlh7bvdh1akqi32iiqiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj8NJOlVObyZz-1CnDggxlXdWYhRlN7PA',
    appId: '1:502997594403:ios:0f36f160fdb130dc945c96',
    messagingSenderId: '502997594403',
    projectId: 'dw-jobtimer',
    storageBucket: 'dw-jobtimer.appspot.com',
    iosClientId: '502997594403-n4hhqvufier2rlh7bvdh1akqi32iiqiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
